#Tensor

## Reshaping, stacking, squeezing and unsqueezing tensors

Reshaping - reshapes an inpute tensor to a defined shape
View - return a view of an input tensor of certain shpae but keep the same tensor (like peeking)
Stacking - combine multiple tensors along a new dimension (vstack, hstack)
Squeezing - remove all 1 dimisions from a tensors
Unsqueeze - add a dimension to a target tensors
Permute - return a View of the input tensors with dimisions permuted in a certain way

In [1]:
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1,9) #(9) -> (1,9), doesn't work with wrong ori dim like != 9
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [7]:
#Try adding an extra dim
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

Reshape meaning that the new dimension has to be equal to the first dim: 1x10 -> 2x5 or 5x2

In [12]:
#Changing the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [27]:
#Stack tensors
x_stacked = torch.stack([x]*9, dim = 1)
x_stacked

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [30]:
x_vstacked = torch.vstack([x]*9)
x_vstacked

x_hstacked = torch.hstack([x]* 9)
x_hstacked

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
#Squeezing and Unsqueezing
x_reshaped_2 = x_reshaped.reshape(1,1,1,1,1,1,9)

## Indexing

In [47]:
#Select data from tensors with indexing
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [48]:
#Let's index on a new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
x[0,0],x[0,1]

(tensor([1, 2, 3]), tensor([4, 5, 6]))

## You can also convert between tensors and numpy array by using torch.Tensor.numpy()

## Reproducibility (Using seeds)



## How to access a GPU for better computation


In [55]:
torch.cuda.is_available()

False

In [59]:
torch.cpu.is_available()
torch.cpu.device_count()

1

In [58]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'